### ISSUE TITLE
Familiar...

### ISSUE THREAD

**Issue by renzo-moran** [indiu6/Classic_Digger_Game#1]
Humm... This project looks familiar to me! :grinning:

**Comment by indiu6** [comment]
> 
> 
> Humm... This project looks familiar to me! 😀

This awesome logic of code, proud of you !! : )

**Comment by indiu6** [comment]
> 
> 
> Humm... This project looks familiar to me! 😀

deleted source code for protecting our work!

**Comment by renzo-moran** [comment]
Deleting was not necessary but thank you my friend! This project was teamwork at its best!
